name: Update AoC Badge in README
on:
  schedule:
    - cron: '23 22 25-31 11 *'
    # - cron: '23 22 1-3 1 *'
    - cron: '23 22 * 12 *'
    
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - uses: tim0-12432/aoc-badge-action@v0.2.0
        with:
          userid: ${{ vars.AOC_USER }}
          session: ${{ secrets.AOC_SESSION }}
          leaderboard: ${{ vars.AOC_LEADERBOARD }}
          width: '35%'

      - continue-on-error: true
        run: |
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git add README.md
            git add aoc-badge.svg
            git commit -m "Update README with AoC badge"
            git push
