name: Update AoC Badge in README
on:
  schedule:
    - cron: '6 5 1-25 12 *'
    
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - uses: tim0-12432/aoc-badge-action
        with:
          userid: ${{ secrets.AOC_USER }}
          session: ${{ secrets.AOC_SESSION }}
          leaderboard: ${{ secrets.AOC_LEADERBOARD }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update AoC badge
          file_pattern: './README.md ./*.svg'
